# Generated by Django 4.1.2 on 2022-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.CharField(max_length=128, unique=True, verbose_name='заголовок')),
                ('short_description', models.CharField(max_length=254, verbose_name='короткое описание')),
                ('description_1', models.TextField(blank=True, max_length=2000, verbose_name='описание - первая половина')),
                ('description_2', models.TextField(blank=True, max_length=2000, verbose_name='описание - вторая половина')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации поста')),
                ('category', models.CharField(max_length=64, verbose_name='Категория')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('image', models.ImageField(upload_to='Основное фото поста')),
                ('extra_img_1', models.ImageField(blank=True, upload_to='Дополнительное фото поста 1')),
                ('extra_img_2', models.ImageField(blank=True, upload_to='Дополнительное фото поста 2')),
                ('extra_img_3', models.ImageField(blank=True, upload_to='Дополнительное фото поста 3')),
                ('extra_img_4', models.ImageField(blank=True, upload_to='Дополнительное фото поста 4')),
                ('extra_img_5', models.ImageField(blank=True, upload_to='Дополнительное фото поста 5')),
                ('tag_1', models.CharField(max_length=16, verbose_name='тэг 1')),
                ('tag_2', models.CharField(max_length=16, verbose_name='тэг 2')),
                ('tag_3', models.CharField(max_length=16, verbose_name='тэг 3')),
                ('tag_4', models.CharField(max_length=16, verbose_name='тэг 4')),
                ('tag_5', models.CharField(max_length=16, verbose_name='тэг 5')),
            ],
        ),
    ]
