# Generated by Django 4.1.2 on 2022-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='extra_img_1',
            field=models.ImageField(blank=True, upload_to='extra_foto'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='extra_img_2',
            field=models.ImageField(blank=True, upload_to='extra_foto'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='extra_img_3',
            field=models.ImageField(blank=True, upload_to='extra_foto'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='extra_img_4',
            field=models.ImageField(blank=True, upload_to='extra_foto'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='extra_img_5',
            field=models.ImageField(blank=True, upload_to='extra_foto'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='main_foto'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tag_1',
            field=models.CharField(blank=True, max_length=16, verbose_name='тэг 1'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tag_2',
            field=models.CharField(blank=True, max_length=16, verbose_name='тэг 2'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tag_3',
            field=models.CharField(blank=True, max_length=16, verbose_name='тэг 3'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tag_4',
            field=models.CharField(blank=True, max_length=16, verbose_name='тэг 4'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tag_5',
            field=models.CharField(blank=True, max_length=16, verbose_name='тэг 5'),
        ),
    ]
