# Generated by Django 4.1.2 on 2022-10-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_posts_extra_img_1_alter_posts_extra_img_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.CharField(max_length=16, verbose_name='продолжительность занятий')),
                ('comment', models.TextField(max_length=254, verbose_name='комментарий')),
                ('photo', models.ImageField(upload_to='comment_photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='extra_img_5',
        ),
    ]
